
schedule:
  configReset: "0 0 23 * * ? *"
  enabled: "true"

app:
  keyCloakAdmin: "mt2-cust-mulesoft"
  secretId: ""
  secretPass: ""      
  enrichFrequency: "0 * * * * ? *"
  schedulerFrequency : "0 0/1 * 1/1 * ? *"
  
keycloak:
  host: "auth.tractmanager.com"
  port: "443"
  realm: "tractmanager"
  username: "mule-connect@tractmanager.com"
  password: ""
  adminRole: "mt2-cust-moffitt"
  
  
port:
  http: "8081"
  https: "8082"

mt2:
  host: "alb.prod.tractsoft.io"
  host-demo: "alb.staging.tractsoft.io"
  port: "443"
  
newrelic:
  environment: "DEV"
  querySince: " SINCE 10 day ago"
    
utils:
  host: "https://sys-tm-utils-sandbox.us-e2.cloudhub.io"
  host2: "https://sys-tm-utils-prod.us-e2.cloudhub.io"
  secretId: "66f15a5f-6fd2-4379-8aba-98421fd9843f"
  secretPass: "d7c632f1-c147-4fca-bcf5-ff01242ebaee"  
  
sysSFTP:
  host: "https://sys-symplr-sftp-prod.us-e2.cloudhub.io"
  secretId: "66f15a5f-6fd2-4379-8aba-98421fd9843f"
  secretPass: "d7c632f1-c147-4fca-bcf5-ff01242ebaee"  

usersLoad:
   host: "meditract1.exavault.com"
   username: "FMOLINT"
   password: "FMOLOracle21!!"
   path: "/Users"
   
pm1:
  host: "sql-demo-01.servers.tractmanager.com"
  port: "1433"
  dbname: "CORPORATE40"
  username: "mulesoft"
  password: "9/QeQNVkPc77K-"

aws:
  access_key_id: "AKIA53NG2F4Q66F75OIO"
  secret_access_key: "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"
  bucket: "mulesoft-dev-symplr"
  queue_url: "https://sqs.us-west-2.amazonaws.com/952221970209/mulesoft-dev-symplr-queue"
  key_prefix:  
    incoming: "CDMI/sContracts/UNC/Incoming"
    processed: "CDMI/sContracts/UNC/Processed"
    errored: "CDMI/sContracts/UNC/Errored"
  importuser:
    staging: "CDMI/Development/sContracts/Staging"
    processed: "CDMI/Development/sContracts"

emissaryservice:
  host: "https://alb.prod.tractsoft.io/emissary"
  email_prefix: "CDMI_"


